FORMAT: 1A
HOST: https://private-09905-askbox.apiary-mock.com/

# Askbox API

# Group Structure of a API

Each API call will return the following structure of data:

        {
            "error": "", // error code
            "error_message": "",
            "data": {}
        }

or

        {
            "error": "",
            "error_message": "",
            "data": [],
            "pagination": {
                offset: 0,
                limit: 10,
                sort: asc, // or desc
                total: 100
            }
        }
        


All the list API call, should have the following parameters:
* query: a string used to filter the list (some API may not have this parameters)
* offset: the starting item to be requested. Default is 0.
* limit: number of items to be retrieving. Default is 10.
* sort: string, should be 'asc' or 'desc'. Default is 'asc'.

HTTP Code

* 200 – OK – Eyerything is working
* 201 – OK – New resource has been created
* 204 – OK – The resource was successfully deleted

* 304 – Not Modified – The client can use cached data

* 400 – Bad Request – The request was invalid or cannot be served. The exact error should be explained in the error payload. E.g. „The JSON is not valid“
* 401 – Unauthorized – The request requires an user authentication
* 403 – Forbidden – The server understood the request, but is refusing it or the access is not allowed.
* 404 – Not found – There is no resource behind the URI.
* 422 – Unprocessable Entity – Should be used if the server cannot process the enitity, e.g. if an image cannot be formatted or mandatory fields are missing in the payload.

* 500 – Internal Server Error – API developers should avoid this error. If an error occurs in the global catch blog, the stracktrace should be logged and not returned as response.

All api datetime format (Timezone: +00:00): YYYY-MM-DDThh:mm:ssTZD (ISO 8601)
For example: 2014-02-22T19:20:21+00:00


# Group Users

## Search Users [/users/search?query={query}&offset={offset}&limit={limit}&sort={sort}]

### /users/search [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "id": 1,
                    "tagline": "testuser",
                    "fullname": "Test User",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                },
                {
                    "id": 2,
                    "tagline": "testuser2",
                    "fullname": "Test User 2",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                },
                {
                    "id": 3,
                    "tagline": "testuser3",
                    "fullname": "Test User 3",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                }
            ]
            
        }

## Featured Users [/users/featured?query={query}&offset={offset}&limit={limit}&sort={sort}]

### /users/featured [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "id": 1,
                    "tagline": "testuser",
                    "fullname": "Test User",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                },
                {
                    "id": 2,
                    "tagline": "testuser2",
                    "fullname": "Test User 2",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                },
                {
                    "id": 3,
                    "tagline": "testuser3",
                    "fullname": "Test User 3",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                }
            ]
            
        }

## Newcomers Users [/users/new?query={query}&offset={offset}&limit={limit}&sort={sort}]

Removed, please don't use this version. Please use the additional version below.

### /users/new [GET]

+ Response 200 (application/json)

        {
            "error": "500",
            "error_message": "Error, we don't use this API. Please use /users/latest instead.",
            "data": []
        }

## Newcomers Users 2 [/users/newcomers?query={query}&offset={offset}&limit={limit}&sort={sort}]

### /users/newcomers [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "id": 111,
                    "tagline": "testuser",
                    "fullname": "Test User",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                },
                {
                    "id": 112,
                    "tagline": "testuser2",
                    "fullname": "Test User 2",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                },
                {
                    "id": 113,
                    "tagline": "testuser3",
                    "fullname": "Test User 3",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                }
            ]
            
        }
        
## Users Collection [/users?offset={offset}&limit={limit}&sort={sort}]

### List Users With Query [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "id": 1,
                    "username": "testuser",
                    "fullname": "Test User",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                },
                {
                    "id": 2,
                    "username": "testuser2",
                    "fullname": "Test User 2",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                },
                {
                    "id": 3,
                    "username": "testuser3",
                    "fullname": "Test User 3",
                    "number_of_followers": 3,
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
                }
            ]
            
        }

## User [/users/{user_id}]

### Get User's profile [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {
                    "id": 1,
                    "username": "testuser",
                    "fullname": "Test User",
                    "tagline": "Make-up",
                    "number_of_followers": 268,
                    "number_of_following": 394,
                    "description": "Obsesses with everything beauty, make-up",
                    "avatar_url": "https://s3-ap-southeast-1.amazonaws.com/askbox.medias/avatar.png",
                    "is_following": false
            }
        }

## User Profile [/users/me]

The `apply_status` field will have the following values:
- `new`: This user is new to the process.
- `pending`: This user applied to be able to receive questions.
- `approved`: This user was approved by admin, to be able to receive questions.

### /users/me [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {
                    "id": 1,
                    "username": "xiaxue",
                    "fullname": "Xia Xue",
                    "tagline": "Make-up",
                    "number_of_followers": 268,
                    "number_of_following": 394,
                    "description": "Obsesses with everything beauty, make-up",
                    "avatar_url": "http://placehold.it/150x150",
                    "email": "abc@gmail.com",
                    "apply_status": "pending"
            }
        }

### /users/me [POST]

+ Request (application/json)

        {
            "tagline": "facebook", // email, facebook, instagram
            "fullname": "",
            "description": "",
            "avatar_url": ""
        }

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {}
        }

## Update User Online status [/users/:user_id/online]

### /users/:user_id/online [POST]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {}
        }


## User email [/users/me/email]

### /users/me/email [GET]

Get user email

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {
                "email": "abc@gmail.com"
            }
        }


### /users/me/email [POST]

Update user email.

+ Request (application/json)

        {
            "email": "xyz@gmail.com"
        }


+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {
                "email": "xyz@gmail.com" //return the email
            }
        }

## User Approval [/users/apply]

The `apply_status` field will have the following values:
- `new`: This user is new to the process.
- `pending`: This user applied to be able to receive questions.
- `approved`: This user was approved by admin, to be able to receive questions.

### /users/apply [POST]

+ Request (application/json)

        {
            "tagline": "facebook"
            "instagram_token": "",
            "email": ""
        }

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {}
        }
        
        
### /users/apply [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {
                "apply_status" : "pending"
            }
        }
        
## Follow User [/follows/{user_to_follow}]

### One user will follow another user [POST]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {}
        }

### One user will unfollow another user [DELETE]

+ Request (application/json)

        {
        }
+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": {}
        }
        
# Group Authentication

## Signup [/auth/signup]

### /auth/signup [POST]

+ Request (application/json)

        {
            "email": "",
            "password": "",
            "username": "",
            "fullname": ""
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": ""
            }


## Local authentication [/auth/local]

### Login using email/username & password [POST]

+ Request (application/json)

        {
            "username": "", // One of
            "email": "",    // these 2 fields
            "password": ""
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJua2hkbyIsImZ1bGxuYW1lIjoiSG9hbmcgRG8iLCJlbWFpbCI6ImhvYW5nZG8uZGg5NEBnbWFpbC5jb20iLCJmYWNlYm9va190b2tlbiI6bnVsbCwiaW5zdGFncmFtX3Rva2VuIjpudWxsLCJpc19hcHByb3ZlZCI6ZmFsc2UsIlByb2ZpbGUiOnsiaWQiOjEsInRhZ2xpbmUiOm51bGwsImRlc2NyaXB0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAxNy0wMi0yM1QxNDo0NzowOS4yMzNaIiwidXBkYXRlZF9hdCI6IjIwMTctMDItMjNUMTQ6NDc6MDkuMjMzWiIsInVzZXJfaWQiOjF9LCJpYXQiOjE0ODc4NjEyNjl9.UUqG_k9c4cu2BSWy_3Wehq_YvNGQMDBiydbtvWRJzpM",
                    "user": {
                        "id": 1,
                        "username": "nkhdo",
                        "fullname": "Hoang Do",
                        "email": "hoangdo.dh94@gmail.com",
                        "tagline": null,
                        "description": null,
                        "avatar_url": null,
                    }
                }
            }

## Facebook authentication [/auth/facebook]

### Login using facebook account [POST]

+ Request (application/json)

        {
            "fbtoken": "token from facebook",
            "user_existed": true,
            "one_signal_playerid": "xxaadd"
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                    "is_existed" : 0,
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJua2hkbyIsImZ1bGxuYW1lIjoiSG9hbmcgRG8iLCJlbWFpbCI6ImhvYW5nZG8uZGg5NEBnbWFpbC5jb20iLCJmYWNlYm9va190b2tlbiI6bnVsbCwiaW5zdGFncmFtX3Rva2VuIjpudWxsLCJpc19hcHByb3ZlZCI6ZmFsc2UsIlByb2ZpbGUiOnsiaWQiOjEsInRhZ2xpbmUiOm51bGwsImRlc2NyaXB0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAxNy0wMi0yM1QxNDo0NzowOS4yMzNaIiwidXBkYXRlZF9hdCI6IjIwMTctMDItMjNUMTQ6NDc6MDkuMjMzWiIsInVzZXJfaWQiOjF9LCJpYXQiOjE0ODc4NjEyNjl9.UUqG_k9c4cu2BSWy_3Wehq_YvNGQMDBiydbtvWRJzpM",
                    "user": {
                        "avatar_url": "https://scontent.xx.fbcdn.net/v/t31.0-1/c141.0.480.480/p480x480/10506738_10150004552801856_220367501106153455_o.jpg?oh=845460c6efc267648343831815cab2b3&oe=59590AFD",
                        "description": "",
                        "email": "wzwibdzulo_1488253007@tfbnw.net",
                        "fullname": "Tom Alaeeccafhjec Putnamsky",
                        "id": 1,
                        "number_of_followers" : 0,
                        "number_of_followings" : 0,
                        "tagline": "",
                        "apply_status" : "pending",
                        "username": "nkhdo"
                        }
                }
            }

## Register device  [/auth/register_device]

### Register device id so that one signal can send push notifications [POST]

Notes: User must login to call this api

+ Request (application/json)

        {
            "one_signal_playerid": "xxaadd"
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                }
            }

## Set minimum price for user question [/users/{user_id}/min_price]

Price is in Dollar.

### /users/{user_id}/min_price [POST]

+ Request (application/json)

        {
            "price": "25" 
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": "success"
            }
            
## Get available coins options [/users/{user_id}/available_coins_option]

The first value of the array is the minimum price.
If the minimum price is 0, it's equivalent to Free.

### /users/{user_id}/available_coins_option [GET]

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": [
                    0,
                    125,
                    250,
                    1000
                ]
            }

# Group Feeds

## Home Feeds [/questions/home?offset={offset}&limit={limit}]

### /questions/home [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "answered_by": {
                        "id": 1111,
                        "username": "Rchlwngx",
                        "fullname": "Rachel Wong",
                        "tagline": "Beauty Blogger, Make-up expert.",
                        "number_of_followers": 268,
                        "number_of_following": 394,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/RachelWong",
                    },
                    
                    "asked_by": {
                        "id": 1112,
                        "username": "Xx",
                        "fullname": "Xia Xue",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 18,
                        "number_of_following": 24,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 1,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 11111,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-11T16:12:27.456Z"
                    
                    
                },
                
                {
                    "answered_by": {
                        "id": 11111,
                        "username": "NRLKheng",
                        "fullname": "Narelle Kheng",
                        "tagline": "Beauty Expert, Freedom Advocate, Blogger.",
                        "number_of_followers": 12,
                        "number_of_following": 34,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/NarelleKheng",
                    },
                    
                    "asked_by": {
                        "id": 11112,
                        "username": "MeltansyB",
                        "fullname": "Melania Tan",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 2,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 11112,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    
                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-11T16:12:27.456Z"
                }
            ]
        }

## Latest Feeds [/questions/latest?offset={offset}&limit={limit}]

### /questions/latest [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "answered_by": {
                        "id": 111111,
                        "username": "Rchlwngx",
                        "fullname": "Rachel Wong",
                        "tagline": "Beauty Blogger, Make-up expert.",
                        "number_of_followers": 268,
                        "number_of_following": 394,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/RachelWong",
                    },
                    
                    "asked_by": {
                        "id": 111112,
                        "username": "Xx",
                        "fullname": "Xia Xue",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 18,
                        "number_of_following": 24,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 1,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 1111111,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    

                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-11T16:12:27.456Z"
                },
                
                {
                    "answered_by": {
                        "id": 11111111,
                        "username": "NRLKheng",
                        "fullname": "Narelle Kheng",
                        "tagline": "Beauty Expert, Freedom Advocate, Blogger.",
                        "number_of_followers": 12,
                        "number_of_following": 34,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/NarelleKheng",
                    },
                    
                    "asked_by": {
                        "id": 11111112,
                        "username": "MeltansyB",
                        "fullname": "Melania Tan",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 2,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 1111112,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    

                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-21T16:12:27.456Z"
                }
            ]
        }

## Profile Feeds - current user's questions [/questions/me?offset={offset}&limit={limit}]

REMOVED, PLEASE USE THE API BELOW

### /questions/me [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "answered_by": {
                        "id": 111111111,
                        "username": "Rchlwngx",
                        "fullname": "Rachel Wong",
                        "tagline": "Beauty Blogger, Make-up expert.",
                        "number_of_followers": 268,
                        "number_of_following": 394,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/RachelWong",
                    },
                    
                    "asked_by": {
                        "id": 111111112,
                        "username": "Xx",
                        "fullname": "Xia Xue",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 18,
                        "number_of_following": 24,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 1,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 1,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    

                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-22T16:12:27.456Z"
                },
                
                {
                    "answered_by": {
                        "id": 1111111111,
                        "username": "NRLKheng",
                        "fullname": "Narelle Kheng",
                        "tagline": "Beauty Expert, Freedom Advocate, Blogger.",
                        "number_of_followers": 12,
                        "number_of_following": 34,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/NarelleKheng",
                    },
                    
                    "asked_by": {
                        "id": 1111111112,
                        "username": "MeltansyB",
                        "fullname": "Melania Tan",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 2,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 2,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    

                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-01T16:12:27.456Z"
                }
            ]
        }

## Profile - all questions and answers for one user [/users/:user_id/questions?offset={offset}&limit={limit}]

### /users/:user_id/questions [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "answered_by": {
                        "id": 111111111,
                        "username": "Rchlwngx",
                        "fullname": "Rachel Wong",
                        "tagline": "Beauty Blogger, Make-up expert.",
                        "number_of_followers": 268,
                        "number_of_following": 394,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/RachelWong",
                    },
                    
                    "asked_by": {
                        "id": 111111112,
                        "username": "Xx",
                        "fullname": "Xia Xue",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 18,
                        "number_of_following": 24,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 1,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 1,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    

                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-22T16:12:27.456Z"
                },
                
                {
                    "answered_by": {
                        "id": 1111111111,
                        "username": "NRLKheng",
                        "fullname": "Narelle Kheng",
                        "tagline": "Beauty Expert, Freedom Advocate, Blogger.",
                        "number_of_followers": 12,
                        "number_of_following": 34,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/NarelleKheng",
                    },
                    
                    "asked_by": {
                        "id": 1111111112,
                        "username": "MeltansyB",
                        "fullname": "Melania Tan",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 2,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 2,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    

                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-01T16:12:27.456Z"
                }
            ]
        }

## Profile - Unlocked questions [/questions/unlocked?offset={offset}&limit={limit}]

REMOVED, PLEASE USE THE API BELOW

### /question/unlocked [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "answered_by": {
                        "id": 11111111111,
                        "username": "Rchlwngx",
                        "fullname": "Rachel Wong",
                        "tagline": "Beauty Blogger, Make-up expert.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "http://placehold.it/150x150"
                    },
                    
                    "asked_by": {
                        "id": 11111111112,
                        "username": "Xx",
                        "fullname": "Xia Xue",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "http://placehold.it/150x150"
                    },
                    
                    "video": {
                        "id": 1,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "length": 54,
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false
                    },
                    
                    "id": 3,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    
                    
                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-01T16:12:27.456Z"
                }
            ]
        }
        
## Profile - Unlocked questions for one user [/users/:user_id/questions_unlocked?offset={offset}&limit={limit}]

### /users/:user_id/questions_unlocked [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "answered_by": {
                        "id": 11111111111,
                        "username": "Rchlwngx",
                        "fullname": "Rachel Wong",
                        "tagline": "Beauty Blogger, Make-up expert.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "http://placehold.it/150x150"
                    },
                    
                    "asked_by": {
                        "id": 11111111112,
                        "username": "Xx",
                        "fullname": "Xia Xue",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "http://placehold.it/150x150"
                    },
                    
                    "video": {
                        "id": 1,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "length": 54,
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false
                    },
                    
                    "id": 3,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    
                    
                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-01T16:12:27.456Z"
                }
            ]
        }
        
        
# Group Questions

## Add question [/questions]

### /questions [POST]

+ Request (application/json)

        {
            "answerer_id": "testuser_2",
            "question": "I want to know about your past.",
            "price": "3", 
            "coins": "25"
            "is_anonymous": true
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": ""
            }
            

## Add answers [/answers]

### /answers [POST]

+ Request (application/json)

        {
            "question_id": 1,
            "video_bucket": "askbox.videos.raw",
            "video_key": "vid012.mov"
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": "success"
            }


## Question Detail [/questions/{question_id}]

### /questions/{question_id} [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "answered_by": {
                        "id": 3,
                        "username": "Rchlwngx",
                        "fullname": "Rachel Wong",
                        "tagline": "Beauty Blogger, Make-up expert.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/RachelWong",
                    },
                    
                    "asked_by": {
                        "id": 2,
                        "username": "Xx",
                        "fullname": "Xia Xue",
                        "tagline": "I am unique, the only unique on in the world.",
                        "number_of_followers": 58,
                        "number_of_following": 21,
                        "description": "Obsesses with everything beauty, make-up",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                    },
                    
                    "video": {
                        "id": 1,
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "video_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/IMG_0629.mp4",
                        "unlocked_by_user": false,
                        "length": 54
                    },
                    
                    "id": 1,
                    "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                    "number_of_likes": 15,
                    "liked_by_me": false,
                    "asked_at": "2017-03-01T16:12:27.456Z",
                    "answered_at": "2017-03-01T16:12:27.456Z"
                }
            ]
        }

## Unlock one question [/questions/{question_id}/unlock]

### /questions/{question_id}/unlock [POST]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": ""
            }

## Like one question [/questions/{question_id}/like]

### /questions/{question_id}/like [POST]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": "success"
            }

## Share one question [/questions/{question_id}/share]

### /questions/{question_id}/share [GET]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": "success"
            }

## View one question [/questions/{question_id}/watch]

### /questions/{question_id}/watch [GET]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": "success"
            }


## Unlike one question [/questions/{question_id}/unlike]

### /questions/{question_id}/unlike [POST]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": "success"
            }

## Ignore one question [/questions/{question_id}/ignore]

### /questions/{question_id}/ignore [POST]

+ Request (application/json)

        {
            "message": "Reason to ignore this question"
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": "success"
            }

## Report one question [/questions/{question_id}/report]

### /questions/{question_id}/report [POST]

+ Request (application/json)

        {
            "message": "Reason to report this question"
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": "success"
            }


## Pending asking [/questions/me/pending_asking]

### /questions/me/pending_asking [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "title": "Asked",
                    "type": 0, 
                    "data": [
                        {
                            "answered_by": {
                                "id": 111111111111,
                                "username": "Rchlwngx",
                                "fullname": "Rachel Wong",
                                "tagline": "Beauty Blogger, Make-up expert.",
                                "number_of_followers": 58,
                                "number_of_following": 21,
                                "description": "Obsesses with everything beauty, make-up",
                                "avatar_url": "https://avatars.io/instagram/RachelWong"
                            },
                            
                            "asked_by": {
                                "id": 111111111112,
                                "username": "Xx",
                                "fullname": "Xia Xue",
                                "tagline": "I am unique, the only unique on in the world.",
                                "number_of_followers": 58,
                                "number_of_following": 21,
                                "description": "Obsesses with everything beauty, make-up",
                                "avatar_url": "https://avatars.io/instagram/XiaXue"
                            },
                            
                            "id": 111,
                            "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                            "number_of_likes": 15,
                            "liked_by_me": false,
                            "price": 20,
                            "asked_at": "2017-05-01T16:12:27.456Z",
                            "deadline": "2017-05-04T16:12:27.456Z"
                        }
                    ]
                },
                {
                    "title": "Asked for Free",
                    "type": 1,
                    "data": [
                        {
                            "answered_by": {
                                "id": 1111111111111,
                                "username": "Rchlwngx",
                                "fullname": "Rachel Wong",
                                "tagline": "Beauty Blogger, Make-up expert.",
                                "number_of_followers": 58,
                                "number_of_following": 21,
                                "description": "Obsesses with everything beauty, make-up",
                                "avatar_url": "https://avatars.io/instagram/RachelWong"
                            },
                            
                            "asked_by": {
                                "id": 1111111111111,
                                "username": "Xx",
                                "fullname": "Xia Xue",
                                "tagline": "I am unique, the only unique on in the world.",
                                "number_of_followers": 58,
                                "number_of_following": 21,
                                "description": "Obsesses with everything beauty, make-up",
                                "avatar_url": "https://avatars.io/instagram/XiaXue"
                            },
                            
                            "id": 112,
                            "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                            "number_of_likes": 15,
                            "liked_by_me": false,
                            "price": 20,
                            "asked_at": "2017-05-01T16:12:27.456Z",
                            "deadline": "2017-05-11T16:12:27.456Z"
                        }
                    ]
                }
            ]
        }


## Pending respond [/questions/me/pending_response]

### /questions/me/pending_response [GET]

+ Response 200 (application/json)

        {
            "error": "",
            "error_message": "",
            "data": [
                {
                    "title": "Answer",
                    "type": 0,
                    "data": [
                        {
                            "answered_by": {
                                "id": 11111111111111,
                                "username": "Rchlwngx",
                                "fullname": "Rachel Wong",
                                "tagline": "Beauty Blogger, Make-up expert.",
                                "number_of_followers": 58,
                                "number_of_following": 21,
                                "description": "Obsesses with everything beauty, make-up",
                                "avatar_url": "https://avatars.io/instagram/RachelWong"
                            },
                            
                            "asked_by": {
                                "id": 11111111111112,
                                "username": "Xx",
                                "fullname": "Xia Xue",
                                "tagline": "I am unique, the only unique on in the world.",
                                "number_of_followers": 58,
                                "number_of_following": 21,
                                "description": "Obsesses with everything beauty, make-up",
                                "avatar_url": "https://avatars.io/instagram/XiaXue"
                            },
                            
                            "id": 1111,
                            "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                            "number_of_likes": 15,
                            "liked_by_me": false,
                            "price": 20,
                            "asked_at": "2017-05-01T16:12:27.456Z",
                            "deadline": "2017-05-01T16:12:27.456Z"
                        }
                    ]
                },
                {
                    "title": "Answer for Free",
                    "type": 1,
                    "data": [
                        {
                            "answered_by": {
                                "id": 111111111111111,
                                "username": "Rchlwngx",
                                "fullname": "Rachel Wong",
                                "tagline": "Beauty Blogger, Make-up expert.",
                                "number_of_followers": 58,
                                "number_of_following": 21,
                                "description": "Obsesses with everything beauty, make-up",
                                "avatar_url": "https://avatars.io/instagram/RachelWong"
                            },
                            
                            "asked_by": {
                                "id": 111111111111112,
                                "username": "Xx",
                                "fullname": "Xia Xue",
                                "tagline": "I am unique, the only unique on in the world.",
                                "number_of_followers": 58,
                                "number_of_following": 21,
                                "description": "Obsesses with everything beauty, make-up",
                                "avatar_url": "https://avatars.io/instagram/XiaXue"
                            },
                            
                            "id": 1112,
                            "question": "Hey Rachel, is there any downsides to being a celebrity in Singapore?",
                            "number_of_likes": 15,
                            "liked_by_me": false,
                            "price": 20,
                            "asked_at": "2017-05-01T16:12:27.456Z",
                            "deadline": "2017-05-01T16:12:27.456Z"
                        }
                    ]
                }
            ]
        }



# Group Media

By default, the medial should be uploaded into S3 buckets using AWS SDK

# Group Activities

We support the following activities: 
* type=0: USER unlocked your question.
* type=1: USER liked the answer to your question.
* type=2: USER started following you.
* type=3: USER answered your question.
* type=4: USER viewed your question.

## Retrieve Activites API [/activities]

### /activities [GET]

+ Response 200 (application/json)

            {
                "error": "",
                "error_message": "",
                "data": [
                    {
                        "id": 1,
                        "type": 0,
                        "question_id": 1,
                        "user_id": 7,
                        "description": "This user unlocked your question",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                        "fullname": "Tony",
                        "cover_url": "",
                        "created_date": "2017-05-01T16:12:27.456Z",
                    },
                    {
                        "id": 2,
                        "type": 1,
                        "question_id": 1,
                        "user_id": 7,
                        "description": "This user liked your question",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                        "fullname": "Tony",
                        "cover_url": "https://dxve5j6gnlkmu.cloudfront.net/1488898739554/frame_0000.png",
                        "created_date": "2017-05-01T16:12:27.456Z",
                    },
                    {
                        "id": 3,
                        "type": 2,
                        "question_id": 1,
                        "user_id": 7,
                        "description": "This user started following your question",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                        "fullname": "Tony",
                        "cover_url": "",
                        "created_date": "2017-05-01T16:12:27.456Z",
                    },
                    {
                        "id": 4,
                        "type": 3,
                        "question_id": 1,
                        "user_id": 7,
                        "description": "This user answered your question",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                        "fullname": "Tony",
                        "cover_url": "",
                        "created_date": "2017-05-01T16:12:27.456Z",
                    },
                    {
                        "id": 5,
                        "type": 4,
                        "question_id": 1,
                        "user_id": 7,
                        "description": "This user viewed your question",
                        "avatar_url": "https://avatars.io/instagram/XiaXue",
                        "fullname": "Tony",
                        "cover_url": "",
                        "created_date": "2017-05-01T16:12:27.456Z",
                    }
                ]
            }

# Group Payment 
(integrate with Stripe)

These APIs would be used by Stripe SDK, the structure of the response 
will be different than the general structure.

## Retrieve Customer API [/customer]

### /customer [GET]

+ Response 200 (application/json)

    + Body
    
            {
              "id": "cus_AEqlGoOKcQHMaJ",
              "object": "customer",
              "account_balance": 0,
              "created": 1488811455,
              "currency": "sgd",
              "default_source": null,
              "delinquent": false,
              "description": null,
              "discount": null,
              "email": null,
              "livemode": false,
              "metadata": {
              },
              "shipping": null,
              "sources": {
                "object": "list",
                "data": [
            
                ],
                "has_more": false,
                "total_count": 0,
                "url": "/v1/customers/cus_AEqlGoOKcQHMaJ/sources"
              }
            }
            
## Attach a new payment source to the Customer for the currently-logged in user [/customer/sources]

https://stripe.com/docs/api#create_card

### /customer/sources [POST]

+ Request (application/json)

        {
            "source": "pack125-499"
        }

+ Response 200 (application/json)

    + Body
    
            {
              "id": "card_19nptJJFZjEDjveklNCrNHkR",
              "object": "card",
              "address_city": null,
              "address_country": null,
              "address_line1": null,
              "address_line1_check": null,
              "address_line2": null,
              "address_state": null,
              "address_zip": null,
              "address_zip_check": null,
              "brand": "Visa",
              "country": "US",
              "customer": "cus_AEqoOMt5uUek1X",
              "cvc_check": null,
              "dynamic_last4": null,
              "exp_month": 8,
              "exp_year": 2018,
              "funding": "credit",
              "last4": "4242",
              "metadata": {
              },
              "name": null,
              "tokenization_method": null
            }

## Select a new default payment source on the Customer for the currently logged-in user [/customer/default_source]

https://stripe.com/docs/api#update_customer

### /customer/default_source [POST]

+ Request (application/json)

        {
            "defaultSource": "pack125-499"
        }

+ Response 200 (application/json)

    + Body
    
            {
              "id": "cus_AErBkSoU0UU5RN",
              "object": "customer",
              "account_balance": 0,
              "created": 1488813014,
              "currency": "sgd",
              "default_source": null,
              "delinquent": false,
              "description": "Customer for sofia.martin@example.com",
              "discount": null,
              "email": null,
              "livemode": false,
              "metadata": {
              },
              "shipping": null,
              "sources": {
                "object": "list",
                "data": [
            
                ],
                "has_more": false,
                "total_count": 0,
                "url": "/v1/customers/cus_AErBkSoU0UU5RN/sources"
              }
            }

# Group Balance

## Get current balance [/users/me/balance]

### /users/me/balance [GET]

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                    "cash" : 15,
                    "coins" : "15.27",
                    "total_earning" : "100.23"
                }
            }

## Inform Cash out [/users/me/cashout]

### /users/me/cashout [POST]
+ Request (application/json)

        {
            "email": "my_paypal_email@gmail.com"
        }
        
+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                    "cash_refunded" : 15
                }
            }


# Group Coins

## Get current Coins [/coins]

### /coins [GET]

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                    "coins" : 15,
                    "unlocks": 10
                }
            }

## Redeem daily bonus [/coins/redeem_daily]

### /coins/redeem_daily [POST]

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                    "coins" : 15,
                    "unlocks" : 20
                }
            }
   
            
## Check redeem daily status [/coins/redeem_status]

### /coins/redeem_status [GET]

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                    "status" : true
                }
            }

## Selling option  [/coins/packs]

### /coins/packs [GET]

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": [
                    {
                        "pack_id": "pack125-499",
                        "coins": 125,
                        "price": 4.99,
                        "tag": "Most popular",
                        "iap_id": "com.askbox.125_coins"
                    },{
                        "pack_id": "pack520-1999",
                        "coins": 520,
                        "price": 19.99,
                        "iap_id": "com.askbox.520_coins"
                    }
                ]
            }


## Buy coins [/coins/buy]

### /coins/buy [POST]

+ Request (application/json)

        {
            "pack_id": "pack125-499"
        }

+ Response 200 (application/json)

    + Body

            {
                "error": "",
                "error_message": "",
                "data": {
                    "coins" : 15 //new coins value
                }
            }
            
            
# Group Settings

## Get push notification settings [/settings/push]

### /settings/push [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "error": "",
                "error_message": "",
                "data": {
                    "push_noti" : true //or false
                }
            }

## Get email notification settings [/settings/email]

### /settings/email [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "error": "",
                "error_message": "",
                "data": {
                    "email_noti" : true //or false
                }
            }

## Set notification settings [/settings/]

### /settings [POST]

+ Request (application/json)

        {
            "push_noti": true, //can ommit
            "email_noti": false //can ommit
        }

+ Response 200 (application/json)

    + Body
    
            {
                "error": "",
                "error_message": "",
                "data": {
                    "email_noti" : true,
                    "push_noti" : true
                }
            }